import { l } from "../localized";
import type { Simulation } from "./types";

/*
 * Simulations run entirely in the browser. Each has a short challenge whose
 * answers are checked on the server with the same models (physics.ts).
 */

export const SIMULATIONS: Simulation[] = [
  {
    id: "projectile",
    subject: "physics",
    area: "simulation",
    difficulty: 2,
    grades: [9, 12],
    title: l("Projectile motion", "სხეულის მოძრაობა ჰორიზონტისადმი კუთხით"),
    summary: l("Launch a ball at any angle and speed on Earth, the Moon or Mars, and see its path, range and height.", "ისროლე ბურთი ნებისმიერი კუთხითა და სიჩქარით დედამიწაზე, მთვარეზე ან მარსზე და ნახე მისი ტრაექტორია, სიშორე და სიმაღლე."),
    explore: [
      l("Keep the speed fixed and try 30°, 45° and 60°. Which goes furthest?", "სიჩქარე უცვლელი დატოვე და სცადე 30°, 45° და 60°. რომელი მიდის ყველაზე შორს?"),
      l("Compare 30° and 60°. What do you notice about the range?", "შეადარე 30° და 60°. რას ამჩნევ სიშორესთან დაკავშირებით?"),
      l("Double the speed. Does the range double too?", "სიჩქარე გააორმაგე. სიშორეც ორმაგდება?"),
      l("Try the Moon. Why does the ball fly so much further?", "სცადე მთვარე. რატომ მიფრინავს ბურთი ბევრად შორს?"),
    ],
    items: [
      {
        type: "choice",
        id: "p-angle",
        prompt: l("On flat ground without air resistance, which launch angle gives the longest range?", "ბრტყელ ზედაპირზე, ჰაერის წინააღმდეგობის გარეშე, სროლის რომელი კუთხე იძლევა უდიდეს სიშორეს?"),
        options: [
          { id: "30", text: l("30°", "30°") },
          { id: "45", text: l("45°", "45°") },
          { id: "60", text: l("60°", "60°") },
          { id: "90", text: l("90°", "90°") },
        ],
        correct: "45",
        explanation: l("Range = v²·sin(2θ)/g, and sin(2θ) is largest (1) when θ = 45°.", "სიშორე = v²·sin(2θ)/g, ხოლო sin(2θ) მაქსიმალურია (1), როცა θ = 45°."),
      },
      {
        type: "choice",
        id: "p-double",
        prompt: l("If you double the launch speed (same angle), what happens to the range?", "თუ სიჩქარეს გააორმაგებ (იგივე კუთხით), რა მოუვა სიშორეს?"),
        options: [
          { id: "same", text: l("It stays the same", "იგივე რჩება") },
          { id: "x2", text: l("It doubles", "ორმაგდება") },
          { id: "x4", text: l("It becomes four times larger", "ოთხჯერ იზრდება") },
          { id: "half", text: l("It halves", "ნახევრდება") },
        ],
        correct: "x4",
        explanation: l("Range depends on v², so twice the speed gives four times the range.", "სიშორე v²-ზეა დამოკიდებული, ამიტომ ორჯერ მეტი სიჩქარე ოთხჯერ მეტ სიშორეს იძლევა."),
      },
      {
        type: "task",
        id: "p-target",
        prompt: l("On Earth, from ground level, hit the target 40 m away (±1.5 m). Set the angle and speed in the simulation, then check.", "დედამიწაზე, მიწის დონიდან, მოარტყი 40 მ-ში მდგომ სამიზნეს (±1,5 მ). სიმულაციაში დააყენე კუთხე და სიჩქარე და შეამოწმე."),
        task: "projectile_target",
        params: { target: 40, tolerance: 1.5 },
        explanation: l("For example, 45° and about 19.8 m/s lands at 40 m; many other pairs work too.", "მაგალითად, 45° და დაახლ. 19,8 მ/წმ 40 მ-ზე ეცემა; სხვა წყვილებიც გამოდგება."),
      },
    ],
  },
  {
    id: "motion",
    subject: "physics",
    area: "simulation",
    difficulty: 1,
    grades: [8, 10],
    title: l("Motion graphs", "მოძრაობის გრაფიკები"),
    summary: l("Set a starting speed and acceleration, watch the car move, and read its position–time and velocity–time graphs.", "დააყენე საწყისი სიჩქარე და აჩქარება, უყურე მანქანის მოძრაობას და წაიკითხე მდებარეობა–დრო და სიჩქარე–დრო გრაფიკები."),
    explore: [
      l("Set acceleration to 0. What shape are the two graphs?", "აჩქარება 0-ზე დააყენე. რა ფორმისაა ორივე გრაფიკი?"),
      l("Add a positive acceleration. How does the position graph change?", "დაამატე დადებითი აჩქარება. როგორ იცვლება მდებარეობის გრაფიკი?"),
      l("Start fast with a negative acceleration. When does the car stop?", "დაიწყე სწრაფად უარყოფითი აჩქარებით. როდის ჩერდება მანქანა?"),
    ],
    items: [
      {
        type: "choice",
        id: "m-flat",
        prompt: l("The velocity–time graph is a horizontal line above zero. What is the car doing?", "სიჩქარე–დრო გრაფიკი ნულის ზემოთ ჰორიზონტალური ხაზია. რას აკეთებს მანქანა?"),
        options: [
          { id: "stopped", text: l("Standing still", "დგას") },
          { id: "constant", text: l("Moving at a constant speed", "მოძრაობს მუდმივი სიჩქარით") },
          { id: "speeding", text: l("Speeding up", "აჩქარებს") },
          { id: "slowing", text: l("Slowing down", "ანელებს") },
        ],
        correct: "constant",
        explanation: l("A flat velocity line means the velocity does not change: constant speed, zero acceleration.", "სიჩქარის ჰორიზონტალური ხაზი ნიშნავს, რომ სიჩქარე არ იცვლება: მუდმივი სიჩქარე, ნულოვანი აჩქარება."),
      },
      {
        type: "choice",
        id: "m-curve",
        prompt: l("The position–time graph curves upwards, getting steeper. What does that mean?", "მდებარეობა–დრო გრაფიკი ზემოთ იხრება და სულ უფრო ციცაბო ხდება. რას ნიშნავს ეს?"),
        options: [
          { id: "speeding", text: l("The car is speeding up", "მანქანა აჩქარებს") },
          { id: "constant", text: l("The car moves at constant speed", "მანქანა მუდმივი სიჩქარით მოძრაობს") },
          { id: "back", text: l("The car is moving backwards", "მანქანა უკან მოძრაობს") },
          { id: "stopped", text: l("The car has stopped", "მანქანა გაჩერდა") },
        ],
        correct: "speeding",
        explanation: l("The slope of a position–time graph is the velocity. A steeper and steeper slope means increasing velocity.", "მდებარეობა–დრო გრაფიკის დახრილობა სიჩქარეა. სულ უფრო ციცაბო დახრილობა მზარდ სიჩქარეს ნიშნავს."),
      },
      {
        type: "numeric",
        id: "m-distance",
        prompt: l("A car starts from rest with acceleration 2 m/s². How far does it travel in 5 s?", "მანქანა უძრაობიდან 2 მ/წმ² აჩქარებით იწყებს მოძრაობას. რა მანძილს გაივლის 5 წამში?"),
        unit: "m",
        answer: 25,
        tolerance: 0.5,
        explanation: l("x = ½·a·t² = ½ · 2 · 5² = 25 m.", "x = ½·a·t² = ½ · 2 · 5² = 25 მ."),
      },
    ],
  },
  {
    id: "circuit",
    subject: "physics",
    area: "electronics",
    difficulty: 2,
    grades: [8, 11],
    title: l("Ohm’s law circuit", "ომის კანონი წრედში"),
    summary: l("Build a circuit with a battery and two resistors in series or in parallel; read the current, voltages and power.", "ააწყე წრედი ბატარეით და ორი რეზისტორით მიმდევრობით ან პარალელურად; წაიკითხე დენი, ძაბვები და სიმძლავრე."),
    explore: [
      l("In series, what happens to the current when you increase one resistor?", "მიმდევრობით შეერთებისას რა ემართება დენს, როცა ერთ რეზისტორს ზრდი?"),
      l("Switch to parallel. Is the total resistance bigger or smaller than each resistor?", "გადართე პარალელურზე. საერთო წინაღობა თითოეულ რეზისტორზე მეტია თუ ნაკლები?"),
      l("In series, add the two voltages. What do you get?", "მიმდევრობით შეერთებისას შეკრიბე ორი ძაბვა. რას იღებ?"),
    ],
    items: [
      {
        type: "numeric",
        id: "c-ohm",
        prompt: l("A 9 V battery is connected to a 45 Ω resistor. What current flows?", "9 ვ ბატარეა 45 Ω რეზისტორთანაა შეერთებული. რა დენი გადის?"),
        unit: "A",
        answer: 0.2,
        tolerance: 0.005,
        explanation: l("I = U ÷ R = 9 ÷ 45 = 0.2 A.", "I = U ÷ R = 9 ÷ 45 = 0,2 ა."),
      },
      {
        type: "numeric",
        id: "c-parallel",
        prompt: l("Two 10 Ω resistors are connected in parallel. What is their total resistance?", "ორი 10 Ω რეზისტორი პარალელურადაა შეერთებული. რა არის მათი საერთო წინაღობა?"),
        unit: "Ω",
        answer: 5,
        tolerance: 0.05,
        explanation: l("For equal resistors in parallel, R = R₁ ÷ 2 = 5 Ω. In general 1/R = 1/R₁ + 1/R₂.", "ტოლი რეზისტორების პარალელური შეერთებისას R = R₁ ÷ 2 = 5 Ω. ზოგადად 1/R = 1/R₁ + 1/R₂."),
      },
      {
        type: "task",
        id: "c-target",
        prompt: l("With the battery at 6 V and the resistors in series, set R₁ and R₂ so the current is 0.25 A (±0.01 A).", "ბატარეა 6 ვ-ზე დააყენე და რეზისტორები მიმდევრობით შეაერთე; R₁ და R₂ ისე შეარჩიე, რომ დენი 0,25 ა იყოს (±0,01 ა)."),
        task: "circuit_current",
        params: { voltage: 6, current: 0.25, tolerance: 0.01, series: 1 },
        explanation: l("You need R₁ + R₂ = 6 ÷ 0.25 = 24 Ω, for example 10 Ω + 14 Ω.", "საჭიროა R₁ + R₂ = 6 ÷ 0,25 = 24 Ω, მაგალითად 10 Ω + 14 Ω."),
      },
    ],
  },
  {
    id: "probability",
    subject: "mathematics",
    area: "simulation",
    difficulty: 1,
    grades: [7, 11],
    title: l("Dice and probability", "კამათლები და ალბათობა"),
    summary: l("Roll one, two or three dice hundreds of times and compare the results with the theoretical probabilities.", "გააგორე ერთი, ორი ან სამი კამათელი ასობითჯერ და შეადარე შედეგები თეორიულ ალბათობებს."),
    explore: [
      l("Roll two dice 10 times, then 1000 times. When does the bar chart look like the theory?", "გააგორე ორი კამათელი 10-ჯერ, შემდეგ 1000-ჯერ. როდის ემსგავსება დიაგრამა თეორიას?"),
      l("Why is 7 the most common sum with two dice?", "რატომ არის 7 ყველაზე ხშირი ჯამი ორი კამათლის შემთხვევაში?"),
      l("What happens to the shape with three dice?", "როგორ იცვლება ფორმა სამი კამათლის შემთხვევაში?"),
    ],
    items: [
      {
        type: "numeric",
        id: "pr-seven",
        prompt: l("What is the probability of rolling a sum of 7 with two fair dice? Give a decimal.", "რა არის ორი სწორი კამათლით 7-ის ჯამის მოგდების ალბათობა? ჩაწერე ათწილადით."),
        unit: "",
        answer: 1 / 6,
        tolerance: 0.005,
        explanation: l("6 of the 36 equally likely outcomes give 7: 6 ÷ 36 = 1/6 ≈ 0.167.", "36 თანაბრად შესაძლო შედეგიდან 6 იძლევა 7-ს: 6 ÷ 36 = 1/6 ≈ 0,167."),
      },
      {
        type: "choice",
        id: "pr-gambler",
        prompt: l("You rolled one die ten times and never got a 6. On the next roll, a 6 is…", "ერთი კამათელი ათჯერ გააგორე და 6 არც ერთხელ მოვიდა. შემდეგ გაგორებაზე 6…"),
        options: [
          { id: "more", text: l("more likely than usual", "ჩვეულებრივზე უფრო სავარაუდოა") },
          { id: "same", text: l("exactly as likely as always: 1/6", "ზუსტად ისევე სავარაუდოა, როგორც ყოველთვის: 1/6") },
          { id: "less", text: l("less likely than usual", "ჩვეულებრივზე ნაკლებად სავარაუდოა") },
          { id: "certain", text: l("certain", "გარანტირებულია") },
        ],
        correct: "same",
        explanation: l("Dice have no memory. Each roll is independent — believing otherwise is the “gambler’s fallacy”.", "კამათელს მეხსიერება არ აქვს. ყოველი გაგორება დამოუკიდებელია — საპირისპიროს რწმენას „მოთამაშის შეცდომა“ ჰქვია."),
      },
      {
        type: "numeric",
        id: "pr-two-sixes",
        prompt: l("What is the probability of getting a double six with two dice? Give a decimal.", "რა არის ორი კამათლით ორი ექვსიანის მოგდების ალბათობა? ჩაწერე ათწილადით."),
        unit: "",
        answer: 1 / 36,
        tolerance: 0.002,
        explanation: l("1/6 × 1/6 = 1/36 ≈ 0.028.", "1/6 × 1/6 = 1/36 ≈ 0,028."),
      },
    ],
  },
  {
    id: "linear-model",
    subject: "mathematics",
    area: "simulation",
    difficulty: 2,
    grades: [9, 12],
    title: l("Fitting a line to data", "წრფის მორგება მონაცემებზე"),
    summary: l("Adjust the slope and intercept of a line to fit spring-stretch data, and watch the error shrink.", "დახრილობისა და თავისუფალი წევრის შეცვლით მოარგე წრფე ზამბარის გაჭიმვის მონაცემებს და უყურე, როგორ მცირდება ცდომილება."),
    explore: [
      l("Move the slope first, then the intercept. Which changes the error more?", "ჯერ დახრილობა შეცვალე, შემდეგ თავისუფალი წევრი. რომელი ცვლის ცდომილებას მეტად?"),
      l("Show the best-fit line. How close did you get?", "აჩვენე საუკეთესო წრფე. რამდენად ახლოს მიხვედი?"),
      l("What does the slope mean physically for the spring?", "რას ნიშნავს დახრილობა ფიზიკურად ზამბარისთვის?"),
    ],
    items: [
      {
        type: "task",
        id: "lm-fit",
        prompt: l("Set a line whose total squared error is within 20% of the best possible line, then check.", "დააყენე წრფე, რომლის კვადრატული ცდომილებების ჯამი საუკეთესო წრფისაზე მაქსიმუმ 20%-ით მეტია, და შეამოწმე."),
        task: "fit_line",
        params: { factor: 1.2 },
        explanation: l("The best line is about y = 0.040x + 0.01: the spring stretches about 0.4 cm per 10 g.", "საუკეთესო წრფე დაახლოებით y = 0,040x + 0,01-ია: ზამბარა ყოველ 10 გ-ზე დაახლ. 0,4 სმ-ით იჭიმება."),
      },
      {
        type: "numeric",
        id: "lm-predict",
        prompt: l("Using the best-fit line, predict the stretch (cm) for a 400 g mass.", "საუკეთესო წრფით იწინასწარმეტყველე გაჭიმვა (სმ) 400 გ მასისთვის."),
        unit: "cm",
        answer: 16.1,
        tolerance: 0.6,
        explanation: l("y ≈ 0.040 × 400 + 0.01 ≈ 16.1 cm — assuming the spring still behaves linearly at 400 g.", "y ≈ 0,040 × 400 + 0,01 ≈ 16,1 სმ — იმ დაშვებით, რომ 400 გ-ზეც ზამბარა წრფივად იქცევა."),
      },
    ],
  },
  {
    id: "growth",
    subject: "mathematics",
    area: "simulation",
    difficulty: 3,
    grades: [10, 12],
    title: l("Population growth models", "პოპულაციის ზრდის მოდელები"),
    summary: l("Compare exponential and logistic growth. Change the growth rate and the carrying capacity and see what limits a population.", "შეადარე ექსპონენციალური და ლოგისტიკური ზრდა. შეცვალე ზრდის ტემპი და გარემოს ტევადობა და ნახე, რა ზღუდავს პოპულაციას."),
    explore: [
      l("With the same rate, when do the two models start to differ?", "ერთნაირი ტემპის დროს როდის იწყებენ ორი მოდელი განსხვავებას?"),
      l("Halve the carrying capacity. What happens to the logistic curve?", "გარემოს ტევადობა განახევრე. რა ემართება ლოგისტიკურ მრუდს?"),
      l("Why can no real population grow exponentially forever?", "რატომ ვერ გაიზრდება რეალური პოპულაცია ექსპონენციალურად უსასრულოდ?"),
    ],
    items: [
      {
        type: "numeric",
        id: "g-exp",
        prompt: l("Exponential model: P₀ = 100, r = 0.5 per hour. What is P after 2 hours? (P = P₀·eʳᵗ)", "ექსპონენციალური მოდელი: P₀ = 100, r = 0,5 საათში. რას უდრის P 2 საათის შემდეგ? (P = P₀·eʳᵗ)"),
        unit: "",
        answer: 100 * Math.E,
        tolerance: 2,
        explanation: l("P = 100·e^(0.5·2) = 100·e ≈ 272.", "P = 100·e^(0,5·2) = 100·e ≈ 272."),
      },
      {
        type: "choice",
        id: "g-limit",
        prompt: l("In the logistic model, what stops the population from growing without limit?", "ლოგისტიკურ მოდელში რა აჩერებს პოპულაციის შეუზღუდავ ზრდას?"),
        options: [
          { id: "rate", text: l("The growth rate becomes negative at the start", "ზრდის ტემპი თავიდანვე უარყოფითი ხდება") },
          { id: "k", text: l("The carrying capacity: limited food, space and resources", "გარემოს ტევადობა: შეზღუდული საკვები, სივრცე და რესურსები") },
          { id: "time", text: l("Time runs out", "დრო იწურება") },
          { id: "nothing", text: l("Nothing — it grows forever", "არაფერი — სამუდამოდ იზრდება") },
        ],
        correct: "k",
        explanation: l("As P approaches the carrying capacity K, growth slows because resources run short.", "როცა P გარემოს ტევადობას K-ს უახლოვდება, ზრდა ნელდება, რადგან რესურსები არ ჰყოფნის."),
      },
    ],
  },
  {
    id: "grid-robot",
    subject: "computing",
    area: "robotics",
    difficulty: 1,
    grades: [6, 10],
    title: l("Program a robot on a grid", "დააპროგრამე რობოტი ბადეზე"),
    summary: l("Write a sequence of commands — forward, turn left, turn right, repeat — to guide a robot to the goal without hitting walls.", "დაწერე ბრძანებების მიმდევრობა — წინ, მარცხნივ, მარჯვნივ, გამეორება — რომ რობოტი კედლებს არ დაეჯახოს და მიზანს მიაღწიოს."),
    explore: [
      l("Plan the route on paper first. Which turns do you need?", "ჯერ მარშრუტი ქაღალდზე დაგეგმე. რომელი მოხვევები გჭირდება?"),
      l("Use “repeat” to make your program shorter.", "გამოიყენე „გამეორება“, რომ პროგრამა შეამოკლო."),
      l("If the robot crashes, which step was wrong? This is debugging.", "თუ რობოტი დაეჯახა, რომელი ნაბიჯი იყო არასწორი? ამას ჰქვია გამართვა."),
    ],
    items: [
      {
        type: "task",
        id: "r-goal",
        prompt: l("Reach the goal (the flag) without crashing, using at most 6 program steps.", "მიაღწიე მიზანს (დროშას) დაჯახების გარეშე, მაქსიმუმ 6 პროგრამული ნაბიჯით."),
        task: "robot_goal",
        params: { maxSteps: 6 },
        explanation: l("One solution: forward ×2, right, forward ×5, left, forward ×3.", "ერთ-ერთი ამოხსნა: წინ ×2, მარჯვნივ, წინ ×5, მარცხნივ, წინ ×3."),
      },
    ],
  },
];

export function findSimulation(id: string) {
  return SIMULATIONS.find((s) => s.id === id) ?? null;
}
