import "server-only";
import fs from "node:fs";
import path from "node:path";
import { getDb, now, parseJson } from "@/lib/db";
import { indexMaterial, uploadDir } from "@/lib/db/material-index";
import { newId } from "@/lib/domain/ids";
import { materialMetaSchema, type MaterialMeta } from "@/lib/domain/schemas";
import type { MaterialVisibility, Subject } from "@/lib/domain/catalog";
import { ApiError } from "@/lib/http/errors";
import type { CurrentUser } from "@/lib/auth/session";
import { extractText, type ExtractedPage } from "@/lib/files/extract";
import { sanitizeFileName, validateUpload } from "@/lib/files/validate";
import { ftsQuery, uniqueTerms } from "@/lib/knowledge/language";
import type { DocumentFormat, IngestWarning } from "@/lib/knowledge/ingest";
import { canView, visibilityClause } from "./material-access";
import { searchKnowledge } from "./knowledge-search";

export { canView } from "./material-access";
export { uploadDir };
export interface MaterialRecord extends MaterialMeta {
  id: string;
  ownerId: string;
  ownerName: string;
  fileName: string;
  mimeType: string;
  sizeBytes: number;
  textStatus: "indexed" | "no_text" | "failed";
  pageCount: number | null;
  chunkCount: number;
  /** How well the text came out of the file (null before indexing). */
  extractionQuality: "good" | "fair" | "poor" | "failed" | null;
  warnings: IngestWarning[];
  createdAt: number;
}

interface MaterialRow {
  id: string;
  owner_id: string;
  owner_name: string;
  title: string;
  subject: Subject;
  grade: number | null;
  author: string;
  tags: string;
  visibility: MaterialVisibility;
  file_name: string;
  stored_name: string;
  mime_type: string;
  size_bytes: number;
  text_status: MaterialRecord["textStatus"];
  page_count: number | null;
  chunk_count: number;
  extraction_quality: MaterialRecord["extractionQuality"];
  warnings: string;
  created_at: number;
}

const SELECT = `SELECT m.*, u.display_name AS owner_name,
  (SELECT COUNT(*) FROM material_chunks c WHERE c.material_id = m.id) AS chunk_count
  FROM materials m JOIN users u ON u.id = m.owner_id`;

function toRecord(row: MaterialRow): MaterialRecord {
  return {
    id: row.id,
    ownerId: row.owner_id,
    ownerName: row.owner_name,
    title: row.title,
    subject: row.subject,
    grade: row.grade,
    author: row.author,
    tags: parseJson<string[]>(row.tags, []),
    visibility: row.visibility,
    fileName: row.file_name,
    mimeType: row.mime_type,
    sizeBytes: row.size_bytes,
    textStatus: row.text_status,
    pageCount: row.page_count,
    chunkCount: row.chunk_count,
    extractionQuality: row.extraction_quality ?? null,
    warnings: parseJson<IngestWarning[]>(row.warnings, []),
    createdAt: row.created_at,
  };
}

export function listMaterials(
  user: CurrentUser,
  filter: { subject?: Subject; grade?: number; q?: string } = {},
): MaterialRecord[] {
  const vis = visibilityClause(user);
  const where = [vis.sql];
  const params: (string | number)[] = [...vis.params];
  if (filter.subject) {
    where.push("m.subject = ?");
    params.push(filter.subject);
  }
  if (filter.grade) {
    where.push("(m.grade = ? OR m.grade IS NULL)");
    params.push(filter.grade);
  }
  if (filter.q?.trim()) {
    const like = `%${filter.q.trim().toLowerCase().replace(/[%_]/g, "")}%`;
    const fts = ftsQuery(uniqueTerms(filter.q));
    where.push(
      `(LOWER(m.title) LIKE ? OR LOWER(m.tags) LIKE ? OR LOWER(m.author) LIKE ?${
        fts ? " OR m.id IN (SELECT c.material_id FROM material_chunks_fts f JOIN material_chunks c ON c.id = f.rowid WHERE material_chunks_fts MATCH ?)" : ""
      })`,
    );
    params.push(like, like, like);
    if (fts) params.push(fts);
  }
  const rows = getDb()
    .prepare(`${SELECT} WHERE ${where.join(" AND ")} ORDER BY m.created_at DESC`)
    .all(...params) as MaterialRow[];
  return rows.map(toRecord);
}

export function getMaterial(id: string, user: CurrentUser): MaterialRecord {
  const row = getDb().prepare(`${SELECT} WHERE m.id = ?`).get(id) as MaterialRow | undefined;
  if (!row) throw new ApiError(404, "not_found");
  const record = toRecord(row);
  if (!canView(record, user)) throw new ApiError(404, "not_found");
  return record;
}

export function getMaterialPreview(id: string, user: CurrentUser, limit = 6): { chunks: { page: number | null; content: string }[] } {
  getMaterial(id, user);
  const chunks = getDb()
    .prepare("SELECT page, content FROM material_chunks WHERE material_id = ? ORDER BY position LIMIT ?")
    .all(id, limit) as { page: number | null; content: string }[];
  return { chunks };
}

export function getMaterialFile(id: string, user: CurrentUser): { path: string; record: MaterialRecord } {
  const record = getMaterial(id, user);
  const row = getDb().prepare("SELECT stored_name FROM materials WHERE id = ?").get(id) as { stored_name: string };
  // stored_name is generated by the server, but basename() keeps reads inside the upload folder regardless.
  return { path: path.join(uploadDir(), path.basename(row.stored_name)), record };
}

/** Stores a validated upload outside the public folder and indexes its text. */
export async function createMaterial(input: {
  owner: CurrentUser;
  meta: MaterialMeta;
  fileName: string;
  bytes: Uint8Array;
  id?: string;
  createdAt?: number;
}): Promise<MaterialRecord> {
  const meta = materialMetaSchema.parse(input.meta);
  const { kind, mime, extension } = validateUpload(input.fileName, input.bytes);
  const id = input.id ?? newId();
  const storedName = `${id}.${extension}`;
  fs.mkdirSync(uploadDir(), { recursive: true });
  fs.writeFileSync(path.join(uploadDir(), storedName), input.bytes, { mode: 0o640 });

  let textStatus: MaterialRecord["textStatus"] = "no_text";
  let pageCount: number | null = null;
  let pages: ExtractedPage[] = [];
  let format: DocumentFormat = "plain";
  try {
    const extracted = await extractText(kind, input.bytes, input.fileName);
    pages = extracted.pages;
    pageCount = extracted.pageCount;
    format = extracted.format;
    textStatus = pages.some((p) => p.text.trim().length > 20) ? "indexed" : "no_text";
  } catch (error) {
    console.warn("[materials] text extraction failed", error instanceof Error ? error.message : error);
    textStatus = "failed";
  }

  getDb()
    .prepare(
      `INSERT INTO materials (id, owner_id, title, subject, grade, author, tags, visibility, file_name, stored_name, mime_type, size_bytes, text_status, page_count, created_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    )
    .run(
      id,
      input.owner.id,
      meta.title,
      meta.subject,
      meta.grade,
      meta.author,
      JSON.stringify(meta.tags),
      meta.visibility,
      sanitizeFileName(input.fileName),
      storedName,
      mime,
      input.bytes.byteLength,
      textStatus,
      pageCount,
      input.createdAt ?? now(),
    );
  if (textStatus === "indexed") {
    const summary = indexMaterial(getDb(), id, pages, format);
    // Text that only looked like text (a scanned PDF's stray characters) yields no passages.
    if (summary.chunks === 0) getDb().prepare("UPDATE materials SET text_status = 'no_text' WHERE id = ?").run(id);
  }
  return getMaterial(id, input.owner);
}

export function updateMaterial(id: string, user: CurrentUser, meta: MaterialMeta): MaterialRecord {
  const record = getMaterial(id, user);
  if (record.ownerId !== user.id && user.role !== "admin") throw new ApiError(403, "forbidden");
  const parsed = materialMetaSchema.parse(meta);
  getDb()
    .prepare("UPDATE materials SET title = ?, subject = ?, grade = ?, author = ?, tags = ?, visibility = ? WHERE id = ?")
    .run(parsed.title, parsed.subject, parsed.grade, parsed.author, JSON.stringify(parsed.tags), parsed.visibility, id);
  return getMaterial(id, user);
}

export function deleteMaterial(id: string, user: CurrentUser): void {
  const { path: filePath, record } = getMaterialFile(id, user);
  if (record.ownerId !== user.id && user.role !== "admin") throw new ApiError(403, "forbidden");
  getDb().prepare("DELETE FROM materials WHERE id = ?").run(id);
  fs.rmSync(filePath, { force: true });
}

export interface RetrievedPassage {
  materialId: string;
  materialTitle: string;
  subject: Subject;
  page: number | null;
  pageEnd: number | null;
  section: string | null;
  content: string;
  score: number;
}

/**
 * Passages from the materials a user may see, best first. The same search
 * the Learning Assistant uses (stemmed Georgian and English terms, BM25,
 * section and quality weighting), limited to uploaded materials.
 */
export function searchPassages(user: CurrentUser, query: string, options: { subject?: Subject; limit?: number; materialIds?: string[] } = {}): RetrievedPassage[] {
  const result = searchKnowledge(user, query, { subject: options.subject, materialIds: options.materialIds, includeLessons: false }, { limit: options.limit ?? 5 });
  return result.passages.map((p) => ({
    materialId: p.sourceId,
    materialTitle: p.sourceTitle,
    subject: p.subject,
    page: p.pageStart,
    pageEnd: p.pageEnd,
    section: p.section,
    content: p.text,
    score: p.score,
  }));
}

export function listMaterialsForLesson(lessonId: string, user: CurrentUser): MaterialRecord[] {
  const ids = (getDb().prepare("SELECT material_id FROM lesson_materials WHERE lesson_id = ?").all(lessonId) as { material_id: string }[]).map(
    (r) => r.material_id,
  );
  return ids
    .map((id) => {
      try {
        return getMaterial(id, user);
      } catch {
        return null;
      }
    })
    .filter((m): m is MaterialRecord => m !== null);
}
