import { l } from "../localized";
import { choice, code, predict, t } from "./builders";
import type { Problem } from "./types";

/* Level 1 — First programs, Level 2 — Core programming. */

export const LEVEL_1_2: Problem[] = [
  code({
    id: "l1-hello",
    level: 1,
    topic: "output",
    difficulty: 1,
    title: l("Hello, Future Classroom!", "გამარჯობა, მომავლის საკლასო ოთახო!"),
    statement: l(
      "Your first program. Print exactly the text Hello, Future Classroom! — with the comma and the exclamation mark.",
      "შენი პირველი პროგრამა. დაბეჭდე ზუსტად ტექსტი Hello, Future Classroom! — მძიმითა და ძახილის ნიშნით.",
    ),
    inputFormat: l("There is no input.", "შემავალი მონაცემები არ არის."),
    outputFormat: l("One line: Hello, Future Classroom!", "ერთი სტრიქონი: Hello, Future Classroom!"),
    constraints: l("—", "—"),
    tests: [t("", "Hello, Future Classroom!", true)],
    hints: [
      l("Which command prints text on the screen in your language?", "რომელი ბრძანება ბეჭდავს ტექსტს ეკრანზე შენს ენაში?"),
      l("Text must be inside quotation marks. Check every character: capital letters, the comma, the space and the !", "ტექსტი ბრჭყალებში უნდა იყოს. შეამოწმე ყველა სიმბოლო: დიდი ასოები, მძიმე, ჰარი და !"),
    ],
    explanation: l("print(...) in Python and cout << ... in C++ send text to standard output. Automatic checkers compare it character by character.", "Python-ში print(...) და C++-ში cout << ... ტექსტს სტანდარტულ გამოსასვლელზე აგზავნის. ავტომატური შემმოწმებელი მას სიმბოლო-სიმბოლო ადარებს."),
    solution: {
      python: 'print("Hello, Future Classroom!")\n',
      cpp: '#include <iostream>\nusing namespace std;\n\nint main() {\n    cout << "Hello, Future Classroom!" << endl;\n    return 0;\n}\n',
    },
  }),
  code({
    id: "l1-greeting",
    level: 1,
    topic: "input",
    difficulty: 1,
    title: l("Personal greeting", "პერსონალური მისალმება"),
    statement: l(
      "Read a name and greet the person: for the name Nino print Hello, Nino! A name can contain spaces.",
      "წაიკითხე სახელი და მიესალმე ადამიანს: სახელისთვის Nino დაბეჭდე Hello, Nino! სახელი შეიძლება ჰარებს შეიცავდეს.",
    ),
    inputFormat: l("One line with the name.", "ერთი სტრიქონი სახელით."),
    outputFormat: l("Hello, <name>!", "Hello, <სახელი>!"),
    constraints: l("The name has 1–50 characters (English letters and spaces).", "სახელი 1–50 სიმბოლოსგან შედგება (ლათინური ასოები და ჰარები)."),
    tests: [t("Nino\n", "Hello, Nino!", true), t("Giorgi\n", "Hello, Giorgi!", true), t("Ana Maria\n", "Hello, Ana Maria!"), t("Z\n", "Hello, Z!")],
    hints: [
      l("First read the whole line into a variable, then print.", "ჯერ მთელი სტრიქონი წაიკითხე ცვლადში, შემდეგ დაბეჭდე."),
      l("In C++, cin >> name stops at the first space. Which function reads the whole line?", "C++-ში cin >> name პირველ ჰარზე ჩერდება. რომელი ფუნქცია კითხულობს მთელ სტრიქონს?"),
      l('Build the answer from three parts: "Hello, ", the name and "!".', 'პასუხი სამი ნაწილისგან ააწყე: "Hello, ", სახელი და "!".'),
    ],
    explanation: l("input() reads a whole line in Python; in C++ use getline(cin, name) so that names with spaces work.", "Python-ში input() მთელ სტრიქონს კითხულობს; C++-ში გამოიყენე getline(cin, name), რომ ჰარიანი სახელებიც იმუშაოს."),
    solution: {
      python: 'name = input()\nprint("Hello, " + name + "!")\n',
      cpp: '#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n    string name;\n    getline(cin, name);\n    cout << "Hello, " << name << "!" << endl;\n    return 0;\n}\n',
    },
  }),
  code({
    id: "l1-rectangle",
    level: 1,
    topic: "arithmetic",
    difficulty: 1,
    title: l("Area and perimeter", "ფართობი და პერიმეტრი"),
    statement: l(
      "A classroom floor is a rectangle with sides a and b metres. Print its area on the first line and its perimeter on the second line.",
      "საკლასო ოთახის იატაკი მართკუთხედია, რომლის გვერდებია a და b მეტრი. პირველ სტრიქონზე დაბეჭდე მისი ფართობი, მეორეზე — პერიმეტრი.",
    ),
    inputFormat: l("Two integers a and b on one line.", "ორი მთელი რიცხვი a და b ერთ სტრიქონზე."),
    outputFormat: l("Two lines: the area, then the perimeter.", "ორი სტრიქონი: ჯერ ფართობი, შემდეგ პერიმეტრი."),
    constraints: l("1 ≤ a, b ≤ 1000", "1 ≤ a, b ≤ 1000"),
    tests: [t("3 4\n", "12\n14", true), t("1 1\n", "1\n4", true), t("1000 999\n", "999000\n3998"), t("7 2\n", "14\n18")],
    hints: [
      l("Area = a · b and perimeter = 2 · (a + b).", "ფართობი = a · b, პერიმეტრი = 2 · (a + b)."),
      l("Both numbers are on one line. In Python, split the line; in C++, cin >> a >> b reads both.", "ორივე რიცხვი ერთ სტრიქონზეა. Python-ში სტრიქონი დაყავი (split); C++-ში cin >> a >> b ორივეს კითხულობს."),
      l("Convert the text to numbers with int(...) before calculating.", "გამოთვლამდე ტექსტი რიცხვად გადააქციე int(...)-ით."),
    ],
    explanation: l("Reading several values from one line is one of the most common input patterns in programming problems.", "ერთი სტრიქონიდან რამდენიმე მნიშვნელობის წაკითხვა ამოცანებში ერთ-ერთი ყველაზე ხშირი შაბლონია."),
    solution: {
      python: "a, b = map(int, input().split())\nprint(a * b)\nprint(2 * (a + b))\n",
      cpp: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int a, b;\n    cin >> a >> b;\n    cout << a * b << \"\\n\" << 2 * (a + b) << \"\\n\";\n    return 0;\n}\n",
    },
  }),
  predict({
    id: "l1-types-predict",
    level: 1,
    topic: "types",
    difficulty: 2,
    title: l("Predict: integer division", "გამოიცანი: მთელრიცხვა გაყოფა"),
    statement: l("Read the program carefully. What exactly does it print? Write the output as one line.", "ყურადღებით წაიკითხე პროგრამა. ზუსტად რას დაბეჭდავს? გამონატანი ერთ სტრიქონად ჩაწერე."),
    code: {
      python: "a = 7\nb = 2\nprint(a // b, a % b, a / b)\n",
      cpp: '#include <iostream>\nusing namespace std;\n\nint main() {\n    int a = 7, b = 2;\n    cout << a / b << " " << a % b << " " << (double)a / b << endl;\n}\n',
    },
    expected: { python: "3 1 3.5", cpp: "3 1 3.5" },
    hints: [
      l("There are three different operations. What does each one mean for whole numbers?", "აქ სამი სხვადასხვა ოპერაციაა. რას ნიშნავს თითოეული მთელი რიცხვებისთვის?"),
      l("One gives the whole part of the division, one gives the remainder, one gives the exact result.", "ერთი გაყოფის მთელ ნაწილს იძლევა, მეორე — ნაშთს, მესამე — ზუსტ შედეგს."),
    ],
    explanation: l("7 // 2 (or 7 / 2 with ints in C++) is 3, the remainder 7 % 2 is 1, and the real division is 3.5.", "7 // 2 (ან C++-ში მთელი რიცხვებით 7 / 2) არის 3, ნაშთი 7 % 2 არის 1, ხოლო ნამდვილი გაყოფა — 3.5."),
  }),
  code({
    id: "l1-even-odd",
    level: 1,
    topic: "conditions",
    difficulty: 1,
    title: l("Even or odd", "ლუწი თუ კენტი"),
    statement: l("Read an integer n and print EVEN if it is even, otherwise ODD. Be careful: n can be negative.", "წაიკითხე მთელი რიცხვი n და დაბეჭდე EVEN, თუ ის ლუწია, წინააღმდეგ შემთხვევაში — ODD. ფრთხილად: n შეიძლება უარყოფითი იყოს."),
    inputFormat: l("One integer n.", "ერთი მთელი რიცხვი n."),
    outputFormat: l("EVEN or ODD.", "EVEN ან ODD."),
    constraints: l("−10⁹ ≤ n ≤ 10⁹", "−10⁹ ≤ n ≤ 10⁹"),
    tests: [t("4\n", "EVEN", true), t("7\n", "ODD", true), t("0\n", "EVEN"), t("-3\n", "ODD"), t("-10\n", "EVEN")],
    hints: [
      l("A number is even when dividing by 2 leaves no remainder.", "რიცხვი ლუწია, როცა 2-ზე გაყოფისას ნაშთი არ რჩება."),
      l("Use the remainder operator % and an if/else.", "გამოიყენე ნაშთის ოპერატორი % და if/else."),
      l("In C++, -3 % 2 is -1, not 1. Compare with 0 instead of with 1.", "C++-ში -3 % 2 არის -1 და არა 1. შეადარე 0-ს და არა 1-ს."),
    ],
    explanation: l("Checking n % 2 == 0 works for negative numbers in every language; checking n % 2 == 1 fails in C++ for negative n.", "შემოწმება n % 2 == 0 უარყოფით რიცხვებზეც ყველა ენაში მუშაობს; n % 2 == 1 კი C++-ში უარყოფითი n-ისთვის ცდება."),
    solution: {
      python: 'n = int(input())\nprint("EVEN" if n % 2 == 0 else "ODD")\n',
      cpp: '#include <iostream>\nusing namespace std;\n\nint main() {\n    long long n;\n    cin >> n;\n    if (n % 2 == 0) cout << "EVEN\\n";\n    else cout << "ODD\\n";\n    return 0;\n}\n',
    },
  }),
  code({
    id: "l1-max-of-three",
    level: 1,
    topic: "conditions",
    difficulty: 2,
    title: l("The largest of three", "სამიდან უდიდესი"),
    statement: l("Three friends measured their jumps. Read three integers and print the largest one.", "სამმა მეგობარმა ნახტომები გაზომა. წაიკითხე სამი მთელი რიცხვი და დაბეჭდე უდიდესი."),
    inputFormat: l("Three integers on one line.", "სამი მთელი რიცხვი ერთ სტრიქონზე."),
    outputFormat: l("The largest number.", "უდიდესი რიცხვი."),
    constraints: l("Each number is between −1000 and 1000.", "თითოეული რიცხვი −1000-სა და 1000-ს შორისაა."),
    tests: [t("3 9 5\n", "9", true), t("-1 -7 -3\n", "-1", true), t("4 4 2\n", "4"), t("0 0 0\n", "0"), t("-5 10 10\n", "10")],
    hints: [
      l("Keep a variable with the best value seen so far.", "შეინახე ცვლადი, რომელშიც აქამდე ნანახი საუკეთესო მნიშვნელობაა."),
      l("Start with the first number, then compare it with the second and the third.", "დაიწყე პირველი რიცხვით, შემდეგ შეადარე მეორეს და მესამეს."),
    ],
    explanation: l("Keeping a 'best so far' variable is the same idea used later to find the maximum of a whole list.", "„აქამდე საუკეთესოს“ ცვლადი იგივე იდეაა, რომლითაც მოგვიანებით მთელი სიის მაქსიმუმს ვიპოვით."),
    solution: {
      python: "a, b, c = map(int, input().split())\nbest = a\nif b > best:\n    best = b\nif c > best:\n    best = c\nprint(best)\n",
      cpp: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int a, b, c;\n    cin >> a >> b >> c;\n    int best = a;\n    if (b > best) best = b;\n    if (c > best) best = c;\n    cout << best << endl;\n    return 0;\n}\n",
    },
  }),
  code({
    id: "l1-sum-to-n",
    level: 1,
    topic: "loops",
    difficulty: 2,
    title: l("Sum from 1 to n", "ჯამი 1-დან n-მდე"),
    statement: l("Read n and print 1 + 2 + … + n.", "წაიკითხე n და დაბეჭდე 1 + 2 + … + n."),
    inputFormat: l("One integer n.", "ერთი მთელი რიცხვი n."),
    outputFormat: l("The sum.", "ჯამი."),
    constraints: l("1 ≤ n ≤ 1 000 000 (the sum can be larger than 2·10⁹)", "1 ≤ n ≤ 1 000 000 (ჯამი შეიძლება 2·10⁹-ზე მეტი იყოს)"),
    tests: [t("5\n", "15", true), t("1\n", "1", true), t("100\n", "5050"), t("1000000\n", "500000500000")],
    hints: [
      l("Use a loop that adds each number from 1 to n to a total.", "გამოიყენე ციკლი, რომელიც ყოველ რიცხვს 1-დან n-მდე ჯამს უმატებს."),
      l("Start the total at 0 before the loop.", "ციკლამდე ჯამი 0-ით დაიწყე."),
      l("For n = 1 000 000 the answer is about 5·10¹¹. In C++ an int holds only about 2·10⁹ — which type is larger?", "n = 1 000 000-ისთვის პასუხი დაახლოებით 5·10¹¹-ია. C++-ში int მხოლოდ ≈2·10⁹-ს იტევს — რომელი ტიპია უფრო დიდი?"),
    ],
    explanation: l("A loop works; so does the formula n·(n+1)/2. In C++ use long long for the total — overflow is a classic contest mistake.", "ციკლიც მუშაობს და ფორმულაც n·(n+1)/2. C++-ში ჯამისთვის გამოიყენე long long — გადავსება ოლიმპიადების კლასიკური შეცდომაა."),
    solution: {
      python: "n = int(input())\ntotal = 0\nfor i in range(1, n + 1):\n    total += i\nprint(total)\n",
      cpp: "#include <iostream>\nusing namespace std;\n\nint main() {\n    long long n;\n    cin >> n;\n    long long total = 0;\n    for (long long i = 1; i <= n; i++) total += i;\n    cout << total << endl;\n    return 0;\n}\n",
    },
  }),
  code({
    id: "l1-times-table",
    level: 1,
    topic: "loops",
    difficulty: 2,
    title: l("Multiplication table", "გამრავლების ტაბულა"),
    statement: l("Read n and print its multiplication table from 1 to 10, one line each, in the format n x i = result.", "წაიკითხე n და დაბეჭდე მისი გამრავლების ტაბულა 1-დან 10-მდე, თითო სტრიქონზე, ფორმატით n x i = შედეგი."),
    inputFormat: l("One integer n.", "ერთი მთელი რიცხვი n."),
    outputFormat: l("10 lines like 3 x 1 = 3.", "10 სტრიქონი, მაგალითად: 3 x 1 = 3."),
    constraints: l("1 ≤ n ≤ 20", "1 ≤ n ≤ 20"),
    tests: [
      t("3\n", Array.from({ length: 10 }, (_, i) => `3 x ${i + 1} = ${3 * (i + 1)}`).join("\n"), true),
      t("7\n", Array.from({ length: 10 }, (_, i) => `7 x ${i + 1} = ${7 * (i + 1)}`).join("\n")),
      t("20\n", Array.from({ length: 10 }, (_, i) => `20 x ${i + 1} = ${20 * (i + 1)}`).join("\n")),
    ],
    hints: [
      l("Repeat the same line 10 times with a loop, changing only i.", "ერთი და იგივე სტრიქონი ციკლით 10-ჯერ გაიმეორე, მხოლოდ i შეცვალე."),
      l("Mind the spaces around x and = — the checker compares text exactly.", "ყურადღება მიაქციე ჰარებს x-ისა და =-ის ირგვლივ — შემმოწმებელი ტექსტს ზუსტად ადარებს."),
    ],
    explanation: l("Formatted output inside a loop: the loop variable i changes, the rest of the line stays the same.", "ფორმატირებული გამოტანა ციკლში: იცვლება მხოლოდ ციკლის ცვლადი i, სტრიქონის დანარჩენი ნაწილი იგივე რჩება."),
    solution: {
      python: 'n = int(input())\nfor i in range(1, 11):\n    print(f"{n} x {i} = {n * i}")\n',
      cpp: '#include <iostream>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    for (int i = 1; i <= 10; i++) {\n        cout << n << " x " << i << " = " << n * i << "\\n";\n    }\n    return 0;\n}\n',
    },
  }),

  // ------------------------------------------------------------------ Level 2
  code({
    id: "l2-list-max-min",
    level: 2,
    topic: "lists",
    difficulty: 1,
    title: l("Highest and lowest temperature", "უმაღლესი და უდაბლესი ტემპერატურა"),
    statement: l("A weather station recorded n temperatures. Print the highest and the lowest, separated by a space.", "ამინდის სადგურმა n ტემპერატურა ჩაიწერა. დაბეჭდე უმაღლესი და უდაბლესი, ჰარით გამოყოფილი."),
    inputFormat: l("First line: n. Second line: n integers.", "პირველი სტრიქონი: n. მეორე სტრიქონი: n მთელი რიცხვი."),
    outputFormat: l("Two numbers: maximum and minimum.", "ორი რიცხვი: მაქსიმუმი და მინიმუმი."),
    constraints: l("1 ≤ n ≤ 1000, each value between −10⁹ and 10⁹", "1 ≤ n ≤ 1000, თითოეული მნიშვნელობა −10⁹-სა და 10⁹-ს შორისაა"),
    tests: [t("5\n3 1 4 1 5\n", "5 1", true), t("1\n-7\n", "-7 -7", true), t("4\n-2 -9 -4 -1\n", "-1 -9"), t("6\n10 20 20 5 0 7\n", "20 0")],
    hints: [
      l("Store the numbers in a list (array) first.", "ჯერ რიცხვები სიაში (მასივში) შეინახე."),
      l("Walk through the list once, updating the best maximum and minimum.", "სია ერთხელ გაიარე და მაქსიმუმი და მინიმუმი თანდათან განაახლე."),
      l("Do not start the maximum at 0 — all numbers could be negative. Start with the first element.", "მაქსიმუმი 0-ით ნუ დაიწყებ — ყველა რიცხვი შეიძლება უარყოფითი იყოს. დაიწყე პირველი ელემენტით."),
    ],
    explanation: l("Initialising with the first element avoids the classic bug of starting max at 0.", "პირველი ელემენტით ინიციალიზაცია თავიდან გაცილებს კლასიკურ შეცდომას — მაქსიმუმის 0-ით დაწყებას."),
    solution: {
      python: "n = int(input())\nvalues = list(map(int, input().split()))\nprint(max(values), min(values))\n",
      cpp: "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    vector<long long> a(n);\n    for (auto &x : a) cin >> x;\n    long long hi = a[0], lo = a[0];\n    for (long long x : a) {\n        if (x > hi) hi = x;\n        if (x < lo) lo = x;\n    }\n    cout << hi << \" \" << lo << endl;\n    return 0;\n}\n",
    },
  }),
  code({
    id: "l2-count-vowels",
    level: 2,
    topic: "strings",
    difficulty: 1,
    title: l("Count the vowels", "დათვალე ხმოვნები"),
    statement: l("Read a line of lowercase English letters and spaces. Count how many vowels (a, e, i, o, u) it contains.", "წაიკითხე სტრიქონი, რომელიც ლათინური პატარა ასოებისა და ჰარებისგან შედგება. დათვალე, რამდენ ხმოვანს (a, e, i, o, u) შეიცავს."),
    inputFormat: l("One line of text.", "ტექსტის ერთი სტრიქონი."),
    outputFormat: l("The number of vowels.", "ხმოვნების რაოდენობა."),
    constraints: l("1–200 characters", "1–200 სიმბოლო"),
    tests: [t("future classroom\n", "6", true), t("rhythm\n", "0", true), t("programming is fun\n", "5"), t("aeiou aeiou\n", "10")],
    hints: [
      l("Look at each character of the string one by one.", "სტრიქონის ყოველი სიმბოლო სათითაოდ განიხილე."),
      l("Check whether the character is one of the five vowels and count it if so.", "შეამოწმე, არის თუ არა სიმბოლო ხუთიდან ერთ-ერთი ხმოვანი, და თუ არის — დაითვალე."),
    ],
    explanation: l("A string is a sequence of characters, so a loop can visit them just like list elements.", "სტრიქონი სიმბოლოების მიმდევრობაა, ამიტომ ციკლს შეუძლია მათი გავლა ისევე, როგორც სიის ელემენტების."),
    solution: {
      python: 'text = input()\nprint(sum(1 for ch in text if ch in "aeiou"))\n',
      cpp: '#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n    string s;\n    getline(cin, s);\n    int count = 0;\n    for (char ch : s)\n        if (ch == \'a\' || ch == \'e\' || ch == \'i\' || ch == \'o\' || ch == \'u\') count++;\n    cout << count << endl;\n    return 0;\n}\n',
    },
  }),
  code({
    id: "l2-palindrome",
    level: 2,
    topic: "strings",
    difficulty: 2,
    title: l("Palindrome check", "პალინდრომის შემოწმება"),
    statement: l("A palindrome reads the same forwards and backwards, like level. Print YES if the word is a palindrome, otherwise NO.", "პალინდრომი ორივე მხრიდან ერთნაირად იკითხება, მაგალითად level. დაბეჭდე YES, თუ სიტყვა პალინდრომია, წინააღმდეგ შემთხვევაში — NO."),
    inputFormat: l("One word of lowercase letters.", "პატარა ასოებით დაწერილი ერთი სიტყვა."),
    outputFormat: l("YES or NO.", "YES ან NO."),
    constraints: l("1–1000 letters", "1–1000 ასო"),
    tests: [t("level\n", "YES", true), t("future\n", "NO", true), t("a\n", "YES"), t("abba\n", "YES"), t("abca\n", "NO")],
    hints: [
      l("Compare the first letter with the last, the second with the second-to-last, and so on.", "შეადარე პირველი ასო ბოლოს, მეორე — ბოლოსწინას და ასე შემდეგ."),
      l("You only need to check up to the middle of the word.", "საკმარისია სიტყვის შუამდე შემოწმება."),
    ],
    explanation: l("In Python, word == word[::-1] compares the word with its reverse; the two-index comparison teaches the same idea step by step.", "Python-ში word == word[::-1] სიტყვას მის შებრუნებულს ადარებს; ორინდექსიანი შედარება იმავე იდეას ნაბიჯ-ნაბიჯ გვასწავლის."),
    solution: {
      python: 'word = input().strip()\nprint("YES" if word == word[::-1] else "NO")\n',
      cpp: '#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n    string s;\n    cin >> s;\n    bool ok = true;\n    for (size_t i = 0, j = s.size() - 1; i < j; i++, j--)\n        if (s[i] != s[j]) ok = false;\n    cout << (ok ? "YES" : "NO") << endl;\n    return 0;\n}\n',
    },
  }),
  code({
    id: "l2-reverse-words",
    level: 2,
    topic: "strings",
    difficulty: 2,
    title: l("Reverse the words", "შეაბრუნე სიტყვები"),
    statement: l("Read a sentence and print its words in reverse order.", "წაიკითხე წინადადება და დაბეჭდე მისი სიტყვები შებრუნებული თანმიმდევრობით."),
    inputFormat: l("One line: words separated by single spaces.", "ერთი სტრიქონი: სიტყვები, თითო ჰარით გამოყოფილი."),
    outputFormat: l("The words in reverse order, separated by single spaces.", "სიტყვები შებრუნებული თანმიმდევრობით, თითო ჰარით გამოყოფილი."),
    constraints: l("1–100 words", "1–100 სიტყვა"),
    tests: [t("i love programming\n", "programming love i", true), t("hello\n", "hello", true), t("one two three four\n", "four three two one")],
    hints: [
      l("Split the sentence into a list of words.", "დაყავი წინადადება სიტყვების სიად."),
      l("Then go through the list from the end to the beginning.", "შემდეგ სია ბოლოდან დასაწყისისკენ გაიარე."),
    ],
    explanation: l("Split → reverse → join is a pattern you will reuse often with text.", "დაყოფა → შებრუნება → გაერთიანება — შაბლონი, რომელსაც ტექსტთან მუშაობისას ხშირად გამოიყენებ."),
    solution: {
      python: 'words = input().split()\nprint(" ".join(reversed(words)))\n',
      cpp: '#include <iostream>\n#include <string>\n#include <vector>\nusing namespace std;\n\nint main() {\n    vector<string> words;\n    string w;\n    while (cin >> w) words.push_back(w);\n    for (int i = (int)words.size() - 1; i >= 0; i--) {\n        cout << words[i];\n        if (i > 0) cout << " ";\n    }\n    cout << endl;\n    return 0;\n}\n',
    },
  }),
  code({
    id: "l2-gcd",
    level: 2,
    topic: "functions",
    difficulty: 2,
    title: l("Greatest common divisor", "უდიდესი საერთო გამყოფი"),
    statement: l(
      "Write a function gcd(a, b) using Euclid's algorithm and use it to print the greatest common divisor of two numbers.",
      "დაწერე ფუნქცია gcd(a, b) ევკლიდეს ალგორითმით და მისი გამოყენებით დაბეჭდე ორი რიცხვის უდიდესი საერთო გამყოფი.",
    ),
    inputFormat: l("Two positive integers a and b.", "ორი დადებითი მთელი რიცხვი a და b."),
    outputFormat: l("gcd(a, b).", "gcd(a, b)."),
    constraints: l("1 ≤ a, b ≤ 10⁹", "1 ≤ a, b ≤ 10⁹"),
    tests: [t("12 18\n", "6", true), t("17 5\n", "1", true), t("100 100\n", "100"), t("1000000000 750000000\n", "250000000")],
    hints: [
      l("Euclid noticed: gcd(a, b) = gcd(b, a mod b).", "ევკლიდემ შეამჩნია: gcd(a, b) = gcd(b, a mod b)."),
      l("Repeat until the second number becomes 0 — then the first number is the answer.", "გაიმეორე, სანამ მეორე რიცხვი 0 არ გახდება — მაშინ პირველი რიცხვია პასუხი."),
      l("Put the loop inside a function that returns the result, then call it once.", "ციკლი ფუნქციაში მოათავსე, რომელიც შედეგს აბრუნებს, და ერთხელ გამოიძახე."),
    ],
    explanation: l("Euclid's algorithm takes only about log steps even for numbers near 10⁹ — much faster than trying every divisor.", "ევკლიდეს ალგორითმს 10⁹-თან ახლო რიცხვებისთვისაც მხოლოდ ლოგარითმული რაოდენობის ნაბიჯი სჭირდება — ბევრად სწრაფად, ვიდრე ყველა გამყოფის გადარჩევას."),
    solution: {
      python: "def gcd(a, b):\n    while b != 0:\n        a, b = b, a % b\n    return a\n\na, b = map(int, input().split())\nprint(gcd(a, b))\n",
      cpp: "#include <iostream>\nusing namespace std;\n\nlong long gcd(long long a, long long b) {\n    while (b != 0) {\n        long long r = a % b;\n        a = b;\n        b = r;\n    }\n    return a;\n}\n\nint main() {\n    long long a, b;\n    cin >> a >> b;\n    cout << gcd(a, b) << endl;\n    return 0;\n}\n",
    },
  }),
  choice({
    id: "l2-debug-average",
    level: 2,
    topic: "debugging",
    difficulty: 2,
    title: l("Debugging: the wrong average", "გამართვა: არასწორი საშუალო"),
    statement: l(
      "This program should print the average of 4, 8, 6 and 5, which is 5.75 — but it prints 4.75. What is the bug?",
      "ამ პროგრამამ 4, 8, 6 და 5-ის საშუალო, ანუ 5.75 უნდა დაბეჭდოს — მაგრამ ბეჭდავს 4.75-ს. სად არის შეცდომა?",
    ),
    code: {
      python: "nums = [4, 8, 6, 5]\ntotal = 0\nfor i in range(1, len(nums)):\n    total += nums[i]\nprint(total / len(nums))\n",
      cpp: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int nums[] = {4, 8, 6, 5};\n    int n = 4;\n    double total = 0;\n    for (int i = 1; i < n; i++) total += nums[i];\n    cout << total / n << endl;\n}\n",
    },
    options: [
      ["a", l("The loop starts at index 1, so the first number is skipped.", "ციკლი ინდექსი 1-დან იწყება, ამიტომ პირველი რიცხვი გამოტოვებულია.")],
      ["b", l("total should start at 1, not 0.", "total 0-ით კი არა, 1-ით უნდა იწყებოდეს.")],
      ["c", l("The program should divide by n − 1.", "პროგრამამ n − 1-ზე უნდა გაყოს.")],
      ["d", l("The division must be integer division.", "გაყოფა მთელრიცხვა უნდა იყოს.")],
    ],
    correct: "a",
    hints: [
      l("Compare the wrong result with the right one: 5.75 − 4.75 = 1 = 4 ÷ 4. Which number is missing from the sum?", "შეადარე არასწორი და სწორი შედეგი: 5.75 − 4.75 = 1 = 4 ÷ 4. რომელი რიცხვი აკლია ჯამს?"),
      l("Indexes start at 0. Which indexes does the loop visit?", "ინდექსები 0-დან იწყება. რომელ ინდექსებს გადის ციკლი?"),
    ],
    explanation: l("The sum is only 8 + 6 + 5 = 19; 19 / 4 = 4.75. Starting the loop at 0 fixes it — an 'off-by-one' error.", "ჯამი მხოლოდ 8 + 6 + 5 = 19-ია; 19 / 4 = 4.75. ციკლის 0-დან დაწყება ასწორებს შეცდომას — ეს „ერთით აცდენის“ შეცდომაა."),
  }),
  choice({
    id: "l2-complexity-pairs",
    level: 2,
    topic: "complexity",
    difficulty: 2,
    title: l("How fast does it grow?", "რამდენად სწრაფად იზრდება?"),
    statement: l(
      "A program compares every student in a class with every other student using two nested loops over n students. When n doubles, the number of comparisons…",
      "პროგრამა ორი ჩადგმული ციკლით კლასის ყველა მოსწავლეს ყველა დანარჩენს ადარებს (n მოსწავლე). როცა n ორმაგდება, შედარებების რაოდენობა…",
    ),
    options: [
      ["a", l("stays the same", "იგივე რჩება")],
      ["b", l("doubles (grows like n)", "ორმაგდება (იზრდება როგორც n)")],
      ["c", l("roughly quadruples (grows like n²)", "დაახლოებით ოთხმაგდება (იზრდება როგორც n²)")],
      ["d", l("grows like 2ⁿ", "იზრდება როგორც 2ⁿ")],
    ],
    correct: "c",
    hints: [
      l("Count the comparisons for n = 10 and n = 20.", "დათვალე შედარებები n = 10-სა და n = 20-ისთვის."),
      l("Each of the n students is compared with about n others.", "n მოსწავლიდან თითოეული დაახლოებით n სხვას ედარება."),
    ],
    explanation: l("Two nested loops over n items do about n·n steps: O(n²). Doubling n multiplies the work by about 4.", "n ელემენტზე ორი ჩადგმული ციკლი დაახლოებით n·n ნაბიჯს აკეთებს: O(n²). n-ის გაორმაგება სამუშაოს დაახლოებით 4-ჯერ ზრდის."),
  }),
  predict({
    id: "l2-predict-stars",
    level: 2,
    topic: "loops",
    difficulty: 1,
    title: l("Predict: nested loop", "გამოიცანი: ჩადგმული ციკლი"),
    statement: l("What does this program print? Write every line of the output.", "რას ბეჭდავს ეს პროგრამა? ჩაწერე გამონატანის ყველა სტრიქონი."),
    code: {
      python: 'for i in range(1, 4):\n    print("*" * i)\n',
      cpp: '#include <iostream>\nusing namespace std;\n\nint main() {\n    for (int i = 1; i <= 3; i++) {\n        for (int j = 0; j < i; j++) cout << "*";\n        cout << "\\n";\n    }\n}\n',
    },
    expected: { python: "*\n**\n***", cpp: "*\n**\n***" },
    hints: [
      l("Which values does i take?", "რა მნიშვნელობებს იღებს i?"),
      l("On each line, the number of stars equals i.", "თითოეულ სტრიქონზე ვარსკვლავების რაოდენობა i-ის ტოლია."),
    ],
    explanation: l("i takes 1, 2, 3, so the lines have 1, 2 and 3 stars.", "i იღებს 1, 2, 3 მნიშვნელობებს, ამიტომ სტრიქონებზე 1, 2 და 3 ვარსკვლავია."),
  }),
];
