import { l } from "../localized";
import { choice, code, predict, t } from "./builders";
import type { Problem } from "./types";

/* Level 3 — Algorithms, Level 4 — Competitive programming (CSES-style). */

export const LEVEL_3_4: Problem[] = [
  code({
    id: "l3-sort",
    level: 3,
    topic: "sorting",
    difficulty: 1,
    title: l("Sort the results", "დაალაგე შედეგები"),
    statement: l("Read n race times and print them in increasing order.", "წაიკითხე n სარბენი დრო და დაბეჭდე ზრდადობით."),
    inputFormat: l("First line: n. Second line: n integers.", "პირველი სტრიქონი: n. მეორე: n მთელი რიცხვი."),
    outputFormat: l("The numbers in increasing order, separated by spaces.", "რიცხვები ზრდადობით, ჰარებით გამოყოფილი."),
    constraints: l("1 ≤ n ≤ 2·10⁵, |aᵢ| ≤ 10⁹", "1 ≤ n ≤ 2·10⁵, |aᵢ| ≤ 10⁹"),
    tests: [t("5\n5 2 9 1 5\n", "1 2 5 5 9", true), t("1\n42\n", "42", true), t("6\n-3 10 0 -3 7 2\n", "-3 -3 0 2 7 10"), t("4\n4 3 2 1\n", "1 2 3 4")],
    hints: [
      l("Both languages have a built-in sort that runs in O(n log n).", "ორივე ენას აქვს ჩაშენებული სორტირება, რომელიც O(n log n) დროში მუშაობს."),
      l("Python: sorted(list). C++: sort(a.begin(), a.end()) from <algorithm>.", "Python: sorted(list). C++: sort(a.begin(), a.end()) <algorithm>-იდან."),
      l("Print the numbers on one line with single spaces between them.", "რიცხვები ერთ სტრიქონზე დაბეჭდე, მათ შორის თითო ჰარით."),
    ],
    explanation: l("For n up to 2·10⁵ a simple O(n²) bubble sort would be too slow; the built-in O(n log n) sort is the right tool.", "n ≤ 2·10⁵-ისთვის მარტივი O(n²) „ბუშტუკოვანი“ სორტირება ძალიან ნელია; ჩაშენებული O(n log n) სორტირება სწორი ინსტრუმენტია."),
    solution: {
      python: 'n = int(input())\na = sorted(map(int, input().split()))\nprint(" ".join(map(str, a)))\n',
      cpp: '#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    vector<long long> a(n);\n    for (auto &x : a) cin >> x;\n    sort(a.begin(), a.end());\n    for (int i = 0; i < n; i++) cout << a[i] << (i + 1 < n ? " " : "\\n");\n    return 0;\n}\n',
    },
  }),
  code({
    id: "l3-binary-search",
    level: 3,
    topic: "searching",
    difficulty: 2,
    title: l("Is it in the list?", "არის თუ არა სიაში?"),
    statement: l(
      "You are given n different numbers in increasing order and q questions. For each question x, print YES if x is in the list, otherwise NO. Use binary search.",
      "მოცემულია ზრდადობით დალაგებული n განსხვავებული რიცხვი და q შეკითხვა. თითოეული x-ისთვის დაბეჭდე YES, თუ x სიაშია, წინააღმდეგ შემთხვევაში — NO. გამოიყენე ორობითი ძებნა.",
    ),
    inputFormat: l("Line 1: n. Line 2: n sorted numbers. Line 3: q. Line 4: q numbers.", "1-ლი სტრიქონი: n. მე-2: n დალაგებული რიცხვი. მე-3: q. მე-4: q რიცხვი."),
    outputFormat: l("q lines with YES or NO.", "q სტრიქონი YES ან NO."),
    constraints: l("1 ≤ n, q ≤ 2·10⁵", "1 ≤ n, q ≤ 2·10⁵"),
    tests: [
      t("5\n1 3 5 7 9\n3\n4 7 9\n", "NO\nYES\nYES", true),
      t("1\n10\n2\n10 11\n", "YES\nNO", true),
      t("6\n-8 -2 0 4 15 100\n5\n-8 100 3 -3 15\n", "YES\nYES\nNO\nNO\nYES"),
    ],
    hints: [
      l("Checking every element for every question takes n·q steps — too slow for the limits.", "ყოველი შეკითხვისთვის ყველა ელემენტის შემოწმება n·q ნაბიჯს მოითხოვს — შეზღუდვებისთვის ძალიან ნელია."),
      l("Look at the middle element: if x is smaller, the answer can only be in the left half.", "შეხედე შუა ელემენტს: თუ x ნაკლებია, პასუხი მხოლოდ მარცხენა ნახევარში შეიძლება იყოს."),
      l("Keep two borders lo and hi and halve the range until it is empty.", "შეინახე ორი საზღვარი lo და hi და შუაზე ყავი დიაპაზონი, სანამ არ დაცარიელდება."),
    ],
    explanation: l("Binary search needs about log₂(n) ≈ 18 steps per question for n = 2·10⁵. Python's bisect and C++'s binary_search do the same.", "ორობით ძებნას n = 2·10⁵-ისთვის ყოველ შეკითხვაზე დაახლოებით log₂(n) ≈ 18 ნაბიჯი სჭირდება. Python-ის bisect და C++-ის binary_search იგივეს აკეთებს."),
    solution: {
      python: 'import bisect\n\nn = int(input())\na = list(map(int, input().split()))\nq = int(input())\nout = []\nfor x in map(int, input().split()):\n    i = bisect.bisect_left(a, x)\n    out.append("YES" if i < n and a[i] == x else "NO")\nprint("\\n".join(out))\n',
      cpp: '#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    vector<long long> a(n);\n    for (auto &x : a) cin >> x;\n    int q;\n    cin >> q;\n    while (q--) {\n        long long x;\n        cin >> x;\n        cout << (binary_search(a.begin(), a.end(), x) ? "YES" : "NO") << "\\n";\n    }\n    return 0;\n}\n',
    },
  }),
  code({
    id: "l3-prefix-sums",
    level: 3,
    topic: "prefix_sums",
    difficulty: 2,
    title: l("Range sums", "შუალედის ჯამები"),
    statement: l(
      "A shop recorded its sales for n days. Answer q questions: what is the total from day l to day r (inclusive, days numbered from 1)?",
      "მაღაზიამ n დღის გაყიდვები ჩაიწერა. უპასუხე q შეკითხვას: რა არის ჯამი l-ური დღიდან r-ურ დღემდე (ჩათვლით, დღეები 1-დან ინომრება)?",
    ),
    inputFormat: l("Line 1: n q. Line 2: n integers. Next q lines: l r.", "1-ლი სტრიქონი: n q. მე-2: n მთელი რიცხვი. შემდეგი q სტრიქონი: l r."),
    outputFormat: l("q lines, one sum each.", "q სტრიქონი, თითოზე ერთი ჯამი."),
    constraints: l("1 ≤ n, q ≤ 2·10⁵, 0 ≤ aᵢ ≤ 10⁹, 1 ≤ l ≤ r ≤ n", "1 ≤ n, q ≤ 2·10⁵, 0 ≤ aᵢ ≤ 10⁹, 1 ≤ l ≤ r ≤ n"),
    tests: [
      t("5 3\n3 1 4 1 5\n1 3\n2 5\n4 4\n", "8\n11\n1", true),
      t("1 1\n7\n1 1\n", "7", true),
      t("4 2\n1000000000 1000000000 1000000000 1000000000\n1 4\n2 3\n", "4000000000\n2000000000"),
    ],
    hints: [
      l("Adding up the range for each question is O(n·q) — too slow.", "ყოველ შეკითხვაზე შუალედის შეკრება O(n·q)-ია — ძალიან ნელი."),
      l("Precompute p[i] = a[1] + … + a[i] once.", "ერთხელ წინასწარ გამოთვალე p[i] = a[1] + … + a[i]."),
      l("Then the sum from l to r is p[r] − p[l − 1]. Use 64-bit integers.", "მაშინ l-დან r-მდე ჯამი არის p[r] − p[l − 1]. გამოიყენე 64-ბიტიანი მთელი რიცხვები."),
    ],
    explanation: l("Prefix sums turn every range query into one subtraction: O(n + q) in total.", "პრეფიქსული ჯამები ყოველ შეკითხვას ერთ გამოკლებად აქცევს: ჯამში O(n + q)."),
    solution: {
      python: 'import sys\n\ndata = sys.stdin.read().split()\nn, q = int(data[0]), int(data[1])\np = [0] * (n + 1)\nfor i in range(n):\n    p[i + 1] = p[i] + int(data[2 + i])\nout = []\nidx = 2 + n\nfor _ in range(q):\n    l, r = int(data[idx]), int(data[idx + 1])\n    idx += 2\n    out.append(str(p[r] - p[l - 1]))\nprint("\\n".join(out))\n',
      cpp: '#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    int n, q;\n    cin >> n >> q;\n    vector<long long> p(n + 1, 0);\n    for (int i = 1; i <= n; i++) {\n        long long x;\n        cin >> x;\n        p[i] = p[i - 1] + x;\n    }\n    while (q--) {\n        int l, r;\n        cin >> l >> r;\n        cout << p[r] - p[l - 1] << "\\n";\n    }\n    return 0;\n}\n',
    },
  }),
  code({
    id: "l3-pair-sum",
    level: 3,
    topic: "two_pointers",
    difficulty: 3,
    title: l("Two numbers with a given sum", "ორი რიცხვი მოცემული ჯამით"),
    statement: l(
      "The array is sorted in non-decreasing order. Is there a pair of numbers at two different positions whose sum is exactly x? Print YES or NO.",
      "მასივი არაკლებადობით არის დალაგებული. არსებობს თუ არა ორ სხვადასხვა პოზიციაზე მდგომი რიცხვების წყვილი, რომელთა ჯამი ზუსტად x-ია? დაბეჭდე YES ან NO.",
    ),
    inputFormat: l("Line 1: n x. Line 2: n sorted integers.", "1-ლი სტრიქონი: n x. მე-2: n დალაგებული მთელი რიცხვი."),
    outputFormat: l("YES or NO.", "YES ან NO."),
    constraints: l("1 ≤ n ≤ 2·10⁵, |aᵢ|, |x| ≤ 10⁹", "1 ≤ n ≤ 2·10⁵, |aᵢ|, |x| ≤ 10⁹"),
    tests: [
      t("5 9\n1 2 4 5 7\n", "YES", true),
      t("4 3\n1 1 1 1\n", "NO", true),
      t("4 2\n1 1 3 5\n", "YES"),
      t("1 10\n5\n", "NO"),
      t("6 -5\n-9 -4 -1 0 3 8\n", "YES"),
    ],
    hints: [
      l("Trying all pairs is O(n²). Can the sorted order help?", "ყველა წყვილის გადარჩევა O(n²)-ია. შეიძლება დალაგებულმა თანმიმდევრობამ დაგვეხმაროს?"),
      l("Put one pointer at the start and one at the end.", "ერთი მაჩვენებელი დასაწყისში დასვი, მეორე — ბოლოში."),
      l("If the sum is too small, move the left pointer right; if too large, move the right pointer left.", "თუ ჯამი ძალიან მცირეა, მარცხენა მაჩვენებელი მარჯვნივ გადაწიე; თუ ძალიან დიდია — მარჯვენა მარცხნივ."),
    ],
    explanation: l("Each step moves one pointer, so the two-pointer scan is O(n). The pointers never cross, which guarantees two different positions.", "ყოველ ნაბიჯზე ერთი მაჩვენებელი მოძრაობს, ამიტომ ორი მაჩვენებლის მეთოდი O(n)-ია. მაჩვენებლები ერთმანეთს არ კვეთს, რაც ორ სხვადასხვა პოზიციას უზრუნველყოფს."),
    solution: {
      python: 'n, x = map(int, input().split())\na = list(map(int, input().split()))\ni, j = 0, n - 1\nfound = False\nwhile i < j:\n    s = a[i] + a[j]\n    if s == x:\n        found = True\n        break\n    if s < x:\n        i += 1\n    else:\n        j -= 1\nprint("YES" if found else "NO")\n',
      cpp: '#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    int n;\n    long long x;\n    cin >> n >> x;\n    vector<long long> a(n);\n    for (auto &v : a) cin >> v;\n    int i = 0, j = n - 1;\n    bool found = false;\n    while (i < j) {\n        long long s = a[i] + a[j];\n        if (s == x) { found = true; break; }\n        if (s < x) i++; else j--;\n    }\n    cout << (found ? "YES" : "NO") << endl;\n    return 0;\n}\n',
    },
  }),
  code({
    id: "l3-fibonacci",
    level: 3,
    topic: "recursion",
    difficulty: 2,
    title: l("Fibonacci numbers", "ფიბონაჩის რიცხვები"),
    statement: l("F(0) = 0, F(1) = 1 and F(n) = F(n − 1) + F(n − 2). Read n and print F(n).", "F(0) = 0, F(1) = 1 და F(n) = F(n − 1) + F(n − 2). წაიკითხე n და დაბეჭდე F(n)."),
    inputFormat: l("One integer n.", "ერთი მთელი რიცხვი n."),
    outputFormat: l("F(n).", "F(n)."),
    constraints: l("0 ≤ n ≤ 90", "0 ≤ n ≤ 90"),
    tests: [t("10\n", "55", true), t("0\n", "0", true), t("1\n", "1"), t("50\n", "12586269025"), t("90\n", "2880067194370816120")],
    hints: [
      l("The definition is recursive, but plain recursion recomputes the same values again and again.", "განმარტება რეკურსიულია, მაგრამ უბრალო რეკურსია ერთსა და იმავე მნიშვნელობებს ისევ და ისევ ითვლის."),
      l("Try F(40) with plain recursion — how long does it take? Remember values you already computed.", "სცადე F(40) უბრალო რეკურსიით — რამდენ ხანს გრძელდება? დაიმახსოვრე უკვე გამოთვლილი მნიშვნელობები."),
      l("Or build the sequence from the bottom: keep the last two numbers in a loop. F(90) needs 64-bit integers.", "ან მიმდევრობა ქვემოდან ააწყე: ციკლში ბოლო ორი რიცხვი შეინახე. F(90)-ს 64-ბიტიანი მთელი რიცხვები სჭირდება."),
    ],
    explanation: l("Plain recursion makes about 1.6ⁿ calls; memoisation or a loop needs only n steps. This is the core idea of dynamic programming.", "უბრალო რეკურსია დაახლოებით 1.6ⁿ გამოძახებას აკეთებს; დამახსოვრებას ან ციკლს მხოლოდ n ნაბიჯი სჭირდება. ეს დინამიკური პროგრამირების ძირითადი იდეაა."),
    solution: {
      python: "n = int(input())\na, b = 0, 1\nfor _ in range(n):\n    a, b = b, a + b\nprint(a)\n",
      cpp: "#include <iostream>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    long long a = 0, b = 1;\n    for (int i = 0; i < n; i++) {\n        long long c = a + b;\n        a = b;\n        b = c;\n    }\n    cout << a << endl;\n    return 0;\n}\n",
    },
  }),
  code({
    id: "l3-brackets",
    level: 3,
    topic: "data_structures",
    difficulty: 3,
    title: l("Balanced brackets", "დაბალანსებული ფრჩხილები"),
    statement: l(
      "A string contains only the characters ( ) [ ] { }. Print YES if every bracket is closed by the matching bracket in the right order, otherwise NO.",
      "სტრიქონი მხოლოდ ( ) [ ] { } სიმბოლოებს შეიცავს. დაბეჭდე YES, თუ ყოველი ფრჩხილი სწორი თანმიმდევრობით შესაბამისი ფრჩხილით იხურება, წინააღმდეგ შემთხვევაში — NO.",
    ),
    inputFormat: l("One line with the brackets.", "ერთი სტრიქონი ფრჩხილებით."),
    outputFormat: l("YES or NO.", "YES ან NO."),
    constraints: l("1–10⁵ characters", "1–10⁵ სიმბოლო"),
    tests: [t("([]{})\n", "YES", true), t("([)]\n", "NO", true), t("(((\n", "NO"), t("{[()()]}\n", "YES"), t(")(\n", "NO")],
    hints: [
      l("Counting opening and closing brackets is not enough: ([)] has equal counts.", "გამხსნელი და დამხურავი ფრჩხილების დათვლა საკმარისი არ არის: ([)]-ში რაოდენობები ტოლია."),
      l("The most recently opened bracket must be closed first. Which data structure works this way?", "ყველაზე ბოლოს გახსნილი ფრჩხილი პირველი უნდა დაიხუროს. რომელი მონაცემთა სტრუქტურა მუშაობს ასე?"),
      l("Push opening brackets onto a stack; on a closing bracket, check and pop the top. At the end the stack must be empty.", "გამხსნელი ფრჩხილები სტეკში ჩადე; დამხურავზე შეამოწმე და ამოიღე ზედა. ბოლოს სტეკი ცარიელი უნდა იყოს."),
    ],
    explanation: l("A stack (last in, first out) matches nested structure: brackets, function calls, undo history.", "სტეკი (ბოლოს შემოსული — პირველი გადის) ჩადგმულ სტრუქტურას შეესაბამება: ფრჩხილებს, ფუნქციების გამოძახებებს, „დაბრუნების“ ისტორიას."),
    solution: {
      python: 's = input().strip()\npairs = {")": "(", "]": "[", "}": "{"}\nstack = []\nok = True\nfor ch in s:\n    if ch in "([{":\n        stack.append(ch)\n    elif not stack or stack.pop() != pairs[ch]:\n        ok = False\n        break\nprint("YES" if ok and not stack else "NO")\n',
      cpp: '#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    string s;\n    cin >> s;\n    stack<char> st;\n    bool ok = true;\n    for (char ch : s) {\n        if (ch == \'(\' || ch == \'[\' || ch == \'{\') st.push(ch);\n        else {\n            char need = ch == \')\' ? \'(\' : ch == \']\' ? \'[\' : \'{\';\n            if (st.empty() || st.top() != need) { ok = false; break; }\n            st.pop();\n        }\n    }\n    cout << (ok && st.empty() ? "YES" : "NO") << endl;\n    return 0;\n}\n',
    },
  }),
  predict({
    id: "l3-recursion-predict",
    level: 3,
    topic: "recursion",
    difficulty: 1,
    title: l("Predict: a recursive function", "გამოიცანი: რეკურსიული ფუნქცია"),
    statement: l("Trace the recursive calls. What does the program print?", "გაადევნე თვალი რეკურსიულ გამოძახებებს. რას ბეჭდავს პროგრამა?"),
    code: {
      python: "def f(n):\n    if n == 0:\n        return 0\n    return n + f(n - 1)\n\nprint(f(4))\n",
      cpp: "#include <iostream>\nusing namespace std;\n\nint f(int n) {\n    if (n == 0) return 0;\n    return n + f(n - 1);\n}\n\nint main() {\n    cout << f(4) << endl;\n}\n",
    },
    expected: { python: "10", cpp: "10" },
    hints: [
      l("Write down f(0) first, then f(1), f(2)… using the ones you already know.", "ჯერ ჩაწერე f(0), შემდეგ f(1), f(2)… უკვე ცნობილი მნიშვნელობების გამოყენებით."),
      l("f(1) = 1 + f(0) = 1, f(2) = 2 + f(1) = 3 …", "f(1) = 1 + f(0) = 1, f(2) = 2 + f(1) = 3 …"),
    ],
    explanation: l("f(4) = 4 + 3 + 2 + 1 + 0 = 10. The base case n == 0 stops the recursion.", "f(4) = 4 + 3 + 2 + 1 + 0 = 10. საბაზისო შემთხვევა n == 0 რეკურსიას აჩერებს."),
  }),

  // ------------------------------------------------------------------ Level 4
  code({
    id: "l4-collatz",
    level: 4,
    topic: "contest",
    difficulty: 1,
    title: l("A strange algorithm", "უცნაური ალგორითმი"),
    statement: l(
      "Start from n. While n is not 1: if n is even, divide it by 2; otherwise replace it with 3n + 1. Print every value of n, including the first and the final 1.",
      "დაიწყე n-იდან. სანამ n არ არის 1: თუ n ლუწია, გაყავი 2-ზე; სხვა შემთხვევაში შეცვალე 3n + 1-ით. დაბეჭდე n-ის ყველა მნიშვნელობა, პირველისა და ბოლო 1-ის ჩათვლით.",
    ),
    inputFormat: l("One integer n.", "ერთი მთელი რიცხვი n."),
    outputFormat: l("The values on one line, separated by spaces.", "მნიშვნელობები ერთ სტრიქონზე, ჰარებით გამოყოფილი."),
    constraints: l("1 ≤ n ≤ 10⁶ (intermediate values can exceed 2·10⁹)", "1 ≤ n ≤ 10⁶ (შუალედური მნიშვნელობები შეიძლება 2·10⁹-ს აჭარბებდეს)"),
    tests: [t("3\n", "3 10 5 16 8 4 2 1", true), t("1\n", "1", true), t("6\n", "6 3 10 5 16 8 4 2 1"), t("7\n", "7 22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1")],
    hints: [
      l("Simulate exactly what the statement says with a while loop.", "ზუსტად ის შეასრულე, რასაც პირობა ამბობს, while ციკლით."),
      l("Print the first value before the loop starts.", "პირველი მნიშვნელობა ციკლის დაწყებამდე დაბეჭდე."),
      l("In C++, 3n + 1 can overflow int — use long long.", "C++-ში 3n + 1 შეიძლება int-ში არ დაეტიოს — გამოიყენე long long."),
    ],
    explanation: l("This is the Collatz sequence. Nobody has proved it always reaches 1, but it does for every n that has been tested.", "ეს კოლაცის მიმდევრობაა. არავის დაუმტკიცებია, რომ ის ყოველთვის 1-ს აღწევს, მაგრამ ყველა შემოწმებული n-ისთვის ასეა."),
    solution: {
      python: 'n = int(input())\nout = [n]\nwhile n != 1:\n    n = n // 2 if n % 2 == 0 else 3 * n + 1\n    out.append(n)\nprint(" ".join(map(str, out)))\n',
      cpp: '#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    long long n;\n    cin >> n;\n    cout << n;\n    while (n != 1) {\n        n = (n % 2 == 0) ? n / 2 : 3 * n + 1;\n        cout << " " << n;\n    }\n    cout << "\\n";\n    return 0;\n}\n',
    },
  }),
  code({
    id: "l4-missing-number",
    level: 4,
    topic: "contest",
    difficulty: 1,
    title: l("The missing number", "გამოტოვებული რიცხვი"),
    statement: l("All numbers from 1 to n except one are given in some order. Find the missing number.", "მოცემულია ყველა რიცხვი 1-დან n-მდე, ერთის გარდა, რაღაც თანმიმდევრობით. იპოვე გამოტოვებული რიცხვი."),
    inputFormat: l("Line 1: n. Line 2: n − 1 distinct integers.", "1-ლი სტრიქონი: n. მე-2: n − 1 განსხვავებული მთელი რიცხვი."),
    outputFormat: l("The missing number.", "გამოტოვებული რიცხვი."),
    constraints: l("2 ≤ n ≤ 2·10⁵", "2 ≤ n ≤ 2·10⁵"),
    tests: [t("5\n2 3 1 5\n", "4", true), t("2\n2\n", "1", true), t("2\n1\n", "2"), t("8\n8 7 6 5 4 3 1\n", "2")],
    hints: [
      l("You do not need to sort. What do you know about 1 + 2 + … + n?", "დალაგება საჭირო არ არის. რა იცი 1 + 2 + … + n-ის შესახებ?"),
      l("Missing number = (sum of 1..n) − (sum of the given numbers). Watch the integer type in C++.", "გამოტოვებული = (1..n-ის ჯამი) − (მოცემული რიცხვების ჯამი). C++-ში ყურადღება მიაქციე მთელი რიცხვის ტიპს."),
    ],
    explanation: l("n(n+1)/2 minus the sum gives the answer in O(n) with O(1) memory. For n = 2·10⁵ the sum is about 2·10¹⁰, so int would overflow.", "n(n+1)/2-ს გამოკლებული ჯამი პასუხს O(n) დროსა და O(1) მეხსიერებაში იძლევა. n = 2·10⁵-ისთვის ჯამი ≈2·10¹⁰-ია, ამიტომ int გადაივსებოდა."),
    solution: {
      python: "n = int(input())\ngiven = sum(map(int, input().split()))\nprint(n * (n + 1) // 2 - given)\n",
      cpp: '#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    long long n;\n    cin >> n;\n    long long sum = 0;\n    for (long long i = 0; i < n - 1; i++) {\n        long long x;\n        cin >> x;\n        sum += x;\n    }\n    cout << n * (n + 1) / 2 - sum << "\\n";\n    return 0;\n}\n',
    },
  }),
  code({
    id: "l4-distinct",
    level: 4,
    topic: "contest",
    difficulty: 2,
    title: l("Distinct values", "განსხვავებული მნიშვნელობები"),
    statement: l("Count how many different values appear in the list.", "დათვალე, რამდენი განსხვავებული მნიშვნელობაა სიაში."),
    inputFormat: l("Line 1: n. Line 2: n integers.", "1-ლი სტრიქონი: n. მე-2: n მთელი რიცხვი."),
    outputFormat: l("The number of distinct values.", "განსხვავებული მნიშვნელობების რაოდენობა."),
    constraints: l("1 ≤ n ≤ 2·10⁵, |aᵢ| ≤ 10⁹", "1 ≤ n ≤ 2·10⁵, |aᵢ| ≤ 10⁹"),
    tests: [t("5\n2 3 2 2 3\n", "2", true), t("1\n7\n", "1", true), t("6\n1 2 3 4 5 6\n", "6"), t("5\n-1 1 -1 1 0\n", "3")],
    hints: [
      l("A set stores each value only once.", "სიმრავლე (set) თითოეულ მნიშვნელობას მხოლოდ ერთხელ ინახავს."),
      l("Or sort the list and count the positions where the value changes.", "ან დაალაგე სია და დათვალე პოზიციები, სადაც მნიშვნელობა იცვლება."),
    ],
    explanation: l("Both a set and sort-then-count are O(n log n) — fast enough for 2·10⁵ numbers.", "როგორც set, ისე დალაგება და დათვლა O(n log n)-ია — 2·10⁵ რიცხვისთვის საკმარისად სწრაფი."),
    solution: {
      python: "n = int(input())\nprint(len(set(input().split())))\n",
      cpp: '#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    vector<long long> a(n);\n    for (auto &x : a) cin >> x;\n    sort(a.begin(), a.end());\n    cout << unique(a.begin(), a.end()) - a.begin() << "\\n";\n    return 0;\n}\n',
    },
  }),
  code({
    id: "l4-max-subarray",
    level: 4,
    topic: "contest",
    difficulty: 3,
    title: l("Best streak", "საუკეთესო სერია"),
    statement: l(
      "A team's daily points can be positive or negative. Find the maximum sum of a non-empty sequence of consecutive days.",
      "გუნდის ყოველდღიური ქულები შეიძლება დადებითი ან უარყოფითი იყოს. იპოვე ზედიზედ მომდევნო დღეების არაცარიელი მიმდევრობის მაქსიმალური ჯამი.",
    ),
    inputFormat: l("Line 1: n. Line 2: n integers.", "1-ლი სტრიქონი: n. მე-2: n მთელი რიცხვი."),
    outputFormat: l("The maximum sum.", "მაქსიმალური ჯამი."),
    constraints: l("1 ≤ n ≤ 2·10⁵, |aᵢ| ≤ 10⁹", "1 ≤ n ≤ 2·10⁵, |aᵢ| ≤ 10⁹"),
    tests: [
      t("8\n-1 3 -2 5 3 -5 2 2\n", "9", true),
      t("3\n-5 -2 -9\n", "-2", true),
      t("1\n4\n", "4"),
      t("5\n1 2 3 4 5\n", "15"),
      t("6\n2 -8 3 -2 4 -10\n", "5"),
    ],
    hints: [
      l("Checking every start and end day is O(n²) or worse.", "ყველა საწყისი და ბოლო დღის გადარჩევა O(n²)-ია ან უარესი."),
      l("Go day by day and keep the best sum of a streak that ends today.", "დღიდან დღემდე იარე და შეინახე იმ სერიის საუკეთესო ჯამი, რომელიც დღეს მთავრდება."),
      l("If the streak ending yesterday has a negative sum, it is better to start again today. Remember the edge case where all numbers are negative.", "თუ გუშინ დასრულებული სერიის ჯამი უარყოფითია, დღეს თავიდან დაწყება სჯობს. გაითვალისწინე შემთხვევა, როცა ყველა რიცხვი უარყოფითია."),
    ],
    explanation: l("This is Kadane's algorithm: best_ending_here = max(a[i], best_ending_here + a[i]). O(n) time, and correct even when every value is negative.", "ეს კადანის ალგორითმია: best_ending_here = max(a[i], best_ending_here + a[i]). O(n) დრო და სწორია მაშინაც, როცა ყველა მნიშვნელობა უარყოფითია."),
    solution: {
      python: "n = int(input())\na = list(map(int, input().split()))\nbest = cur = a[0]\nfor x in a[1:]:\n    cur = max(x, cur + x)\n    best = max(best, cur)\nprint(best)\n",
      cpp: '#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    vector<long long> a(n);\n    for (auto &x : a) cin >> x;\n    long long best = a[0], cur = a[0];\n    for (int i = 1; i < n; i++) {\n        cur = max(a[i], cur + a[i]);\n        best = max(best, cur);\n    }\n    cout << best << "\\n";\n    return 0;\n}\n',
    },
  }),
  code({
    id: "l4-repetitions",
    level: 4,
    topic: "contest",
    difficulty: 2,
    title: l("Longest repetition", "ყველაზე გრძელი გამეორება"),
    statement: l("A DNA sequence is a string of the letters A, C, G and T. Find the length of the longest block of the same letter in a row.", "დნმ-ის მიმდევრობა A, C, G და T ასოების სტრიქონია. იპოვე ზედიზედ მდგომი ერთნაირი ასოების ყველაზე გრძელი ბლოკის სიგრძე."),
    inputFormat: l("One string.", "ერთი სტრიქონი."),
    outputFormat: l("The length of the longest block.", "ყველაზე გრძელი ბლოკის სიგრძე."),
    constraints: l("1 ≤ length ≤ 10⁶", "1 ≤ სიგრძე ≤ 10⁶"),
    tests: [t("ATTCGGGA\n", "3", true), t("A\n", "1", true), t("ACGT\n", "1"), t("GGGGGG\n", "6"), t("AACCCGTTTTA\n", "4")],
    hints: [
      l("Walk through the string once, keeping the length of the current block.", "სტრიქონი ერთხელ გაიარე და მიმდინარე ბლოკის სიგრძე შეინახე."),
      l("When the letter changes, reset the current length to 1. Update the best after every step.", "როცა ასო იცვლება, მიმდინარე სიგრძე 1-ზე დააბრუნე. ყოველი ნაბიჯის შემდეგ საუკეთესო განაახლე."),
    ],
    explanation: l("One pass, O(n). Remember to update the answer inside the loop, not only when a block ends — otherwise the last block is missed.", "ერთი გავლა, O(n). პასუხი ციკლის შიგნით განაახლე და არა მხოლოდ ბლოკის დასრულებისას — თორემ ბოლო ბლოკი გამოგრჩება."),
    solution: {
      python: "s = input().strip()\nbest = cur = 1\nfor i in range(1, len(s)):\n    cur = cur + 1 if s[i] == s[i - 1] else 1\n    best = max(best, cur)\nprint(best)\n",
      cpp: '#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    string s;\n    cin >> s;\n    int best = 1, cur = 1;\n    for (size_t i = 1; i < s.size(); i++) {\n        cur = (s[i] == s[i - 1]) ? cur + 1 : 1;\n        best = max(best, cur);\n    }\n    cout << best << "\\n";\n    return 0;\n}\n',
    },
  }),
  choice({
    id: "l4-constraints",
    level: 4,
    topic: "complexity",
    difficulty: 2,
    title: l("Reading the constraints", "შეზღუდვების წაკითხვა"),
    statement: l(
      "A problem has n ≤ 2·10⁵ and a time limit of 1 second. A computer does roughly 10⁸ simple operations per second. Which approach is fast enough?",
      "ამოცანაში n ≤ 2·10⁵ და დროის ლიმიტი 1 წამია. კომპიუტერი წამში დაახლოებით 10⁸ მარტივ ოპერაციას ასრულებს. რომელი მიდგომაა საკმარისად სწრაფი?",
    ),
    options: [
      ["a", l("O(n²): compare every pair", "O(n²): ყველა წყვილის შედარება")],
      ["b", l("O(n log n): sort, then scan once", "O(n log n): დალაგება და ერთხელ გავლა")],
      ["c", l("O(n³): three nested loops", "O(n³): სამი ჩადგმული ციკლი")],
      ["d", l("O(2ⁿ): try every subset", "O(2ⁿ): ყველა ქვესიმრავლის გადარჩევა")],
    ],
    correct: "b",
    hints: [
      l("Put n = 200 000 into each formula.", "ჩასვი n = 200 000 თითოეულ ფორმულაში."),
      l("n² = 4·10¹⁰ — how many seconds is that at 10⁸ operations per second?", "n² = 4·10¹⁰ — რამდენი წამია ეს წამში 10⁸ ოპერაციის სიჩქარით?"),
    ],
    explanation: l("n log n ≈ 2·10⁵ · 18 ≈ 3.6·10⁶ operations: fine. n² ≈ 4·10¹⁰ would take minutes. Reading the constraints tells you which algorithm is expected.", "n log n ≈ 2·10⁵ · 18 ≈ 3.6·10⁶ ოპერაცია: კარგია. n² ≈ 4·10¹⁰ წუთებს წაიღებდა. შეზღუდვების წაკითხვა გეუბნება, რომელი ალგორითმია მოსალოდნელი."),
  }),
  choice({
    id: "l4-overflow",
    level: 4,
    topic: "contest",
    difficulty: 1,
    title: l("Edge case: overflow", "ზღვრული შემთხვევა: გადავსება"),
    statement: l(
      "In C++ you add up to 2·10⁵ numbers, each up to 10⁹. Which type should the total have?",
      "C++-ში 2·10⁵-მდე რიცხვს კრებ, თითოეული 10⁹-მდე. რა ტიპის უნდა იყოს ჯამი?",
    ),
    options: [
      ["a", l("int", "int")],
      ["b", l("long long", "long long")],
      ["c", l("char", "char")],
      ["d", l("float", "float")],
    ],
    correct: "b",
    hints: [
      l("What is the largest possible total?", "რა არის ყველაზე დიდი შესაძლო ჯამი?"),
      l("int holds values up to about 2.1·10⁹.", "int დაახლოებით 2.1·10⁹-მდე მნიშვნელობებს იტევს."),
    ],
    explanation: l("The total can reach 2·10¹⁴, far beyond int. long long holds up to about 9.2·10¹⁸. float would lose precision.", "ჯამმა შეიძლება 2·10¹⁴-ს მიაღწიოს, int-ის საზღვარზე ბევრად მეტს. long long ≈9.2·10¹⁸-მდე იტევს. float სიზუსტეს დაკარგავდა."),
  }),
];
